Fix errors after set strict mode to true
* error TS2564: Property 'activity' has no initializer and is not definitely assigned in the constructor
* error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Activity'
* error TS2322: Type 'string' is not assignable to type 'boolean'
* error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'